version: '3'
services: 
    db:
        build:
            context: .
            dockerfile: ./db/Dockerfile
            args:
                - DB_LANG=ja_JP
        environment:
            - POSTGRES_USER=kamakurashuuhei
            - POSTGRES_PASSWORD=1
            - POSTGRES_DB=
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - ./db:/usr/local/bin/postgres
    frontend:
        build: 
            context: .
            dockerfile: ./totonoe-app/Dockerfile
        depends_on: 
            - db
        volumes:
            - ./totonoe-app:/frontend/src
        ports: 
            - 3000:3000
        tty: true
        stdin_open: true
        environment: 
            - CHOKIDAR_USEPOLLING=true
        command: sh -c "npm start"
    backend:
        build: 
            context: .
            dockerfile: ./backend/Dockerfile
        depends_on: 
            - db
        tty: true
        volumes:
            - ./backend:/backend
        # ports:
        #     - 4000:4000