version: '3'
services: 
    totonoe:
        container_name: totonoe
        build:
            context: .
            dockerfile: ./db/Dockerfile
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: totonoe
        ports:
            - 5432:5432
        volumes:
            - ./db:/usr/local/bin/postgres
        networks:
            - totonoe-network
    frontend:
        build: 
            context: .
            dockerfile: ./totonoe-app/Dockerfile
        depends_on: 
            - totonoe
        volumes:
            - ./totonoe-app:/frontend/src
        ports: 
            - 3000:3000
        tty: true
        stdin_open: true
        environment: 
            - CHOKIDAR_USEPOLLING=true
        command: sh -c "npm start"
        networks:
            - totonoe-network
    backend:
        build: 
            context: .
            dockerfile: ./backend/Dockerfile
        depends_on: 
            - totonoe
        tty: true
        volumes:
            - ./backend:/backend
        ports:
            - 4000:4000
        command: go run main.go
        networks:
            - totonoe-network
networks: 
    totonoe-network:
        external: true