name: CI

on:
    [ push ]

env:
    COMPOSE_FILE: '../../docker-compose.yml'

jobs:
    docker-build:
        runs-on: ubuntu-latest
        # 10分
        timeout-minutes: 10

        #アクションを定義
        steps:
        -   name: checkout pushed commit
            # ソースコードをチェックアウト
            uses: actions/checkout@v3
            with:
            # PRのHEADブランチを使う
             ref: ${{ github.event.pull_request.head.sha }}
        
        # Docker Composeで実行する
        -   name: run test on docker-compose
            run: |
                docker-compose -f ${COMPOSE_FILE}
