name: CI

on:
    [ push ]

env:
    COMPOSE_FILE: '../../docker-compose.yml'

jobs:
    docker-build:
        runs-on: ubuntu-latest
        # 10分
        timeout-minutes: 10

        #アクションを定義
        steps:
        -   name: checkout pushed commit
            # ソースコードをチェックアウト
            uses: actions/checkout@v3
            with:
            # PRのHEADブランチを使う
             ref: ${{ github.event.pull_request.head.sha }}

        # Docker Composeで実行する
        -   name: run test on docker-compose
            run: |
                docker-compose up -d -f COMPOSE_FILE

        # フロントエンドのサービスが立ち上がるまで待機する
        -   name: Wait for services to start
            run: docker-compose run --rm totonoe_frontend_1 sh -c "while ! nc -z api 3000; do sleep 1; done"
        
        # フロントエンドのテストを実行する
        -   name: Run frontend tests
            run: |
              docker-compose exec totonoe_frontend_1 npm run test
        
        # dokcer compose
        -    name: Stop docker-compose
             run: docker-compose down
